version: "3.10"
services:
  worker:
    build: .
    environment:
      SESSION_NAME: $SESSION_NAME
      MUST_JOIN: $MUST_JOIN
      GROUP: $GROUP
      CHANNEL: $CHANNEL
      API_ID: $API_ID
      API_HASH: $API_HASH
      MONGO_DB_URI: $MONGO_DB_URI
      LOG_GROUP_ID: $LOG_GROUP_ID
      BOT_TOKEN: $BOT_TOKEN
      MUSIC_BOT_NAME: $MUSIC_BOT_NAME
      OWNER_ID: $OWNER_ID
      ASS_ID: $ASS_ID
      DURATION_LIMIT: $DURATION_LIMIT
      LOG_GROUP_ID_2: $LOG_GROUP_ID_2
      SUDO_USERS: $SUDO_USERS
      UPSTREAM_BRANCH: $UPSTREAM_BRANCH
      UPSTREAM_REPO: $UPSTREAM_REPO
